server.port=8080
#baseuri=app.86-119-40-54.se.scs.unisg.ch/

spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# uncomment the following for using the remote database in the provided VM
#spring.datasource.url=jdbc:mysql://86.119.40.54:3306/carlease
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=pkjFx3sgoKuxe_Jck9Nu
#spring.sql.init.mode=always

# uncomment the following for using the embedded H2 database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

logging.level.root=info
spring.profiles.active=dev
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n
logging.file.path=logs
logging.file.name=${logging.file.path}/log.log
logging.pattern.file=%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n